Quiz
iam-hbk/pave pull request #17
Opened 2023-10-02 21:43 UTC by iam-hbk

2023-10-02 22:10 UTC, KenanK0 commented
**Some import are incorrect and they prevent the code from running**

**in Profile**
`- import LeaderboardItem from "@/components/leaderboardItem"; 
`
instead of 
`- import LeaderboardItem from "@/components/LeaderboardItem";`


**in home header and coin Header**
`import CoinIconAndAmount from "./coinIconAndAmount";`
instead of
`import CoinIconAndAmount from "./CoinIconAndAmount";`

> Keep pushing

2023-10-02 22:13 UTC, KenanK0 requested changes

2023-10-02 22:13 UTC, KenanK0 commented on app/(app)/profile/index.tsx
> +
comme ca vraiment

2023-10-02 22:13 UTC, KenanK0 commented on components/homeHeader.tsx
> +import CoinIconAndAmount from "./coinIconAndAmount";
Merci

2023-10-02 22:13 UTC, KenanK0 commented on components/coinHeader.tsx
> +import CoinIconAndAmount from "./coinIconAndAmount";
donc tu as seulement changer l'import

2023-10-03 17:31 UTC, iam-hbk commented on components/homeHeader.tsx
> +import CoinIconAndAmount from "./coinIconAndAmount";
Eish !😂😂

2023-10-03 18:48 UTC, KenanK0 approved these changes
good

2023-10-03 18:48 UTC, merged